/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 6cc6df8cee61d702b9e6f73c7368b848)
declare namespace Cloudflare {
	interface Env {
		CHAT_AGENT_NAMESPACE_KEBABCASE: string;
		CHAT_AGENT_ID: string;
		CHAT_AGENT_DO_NAMESPACE: DurableObjectNamespace<import("./src/worker").ChatAgentDO>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CHAT_AGENT_NAMESPACE_KEBABCASE" | "CHAT_AGENT_ID">> {}
}
